### ISSUE TITLE
How to deal with exceptions? (and other beginner notes)

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [pragmagic/godot-nim#113]
Specifically the situation that I ran into was when a line_edit node is empty. I thought I found the answer:

` proc on_inbox_text_changed(intext:string) {.gdExport, raises:[IndexDefect, Exception].} =`

But this does not seem to change anything (exception still occurs from this signal, all code still doesn't run when this occurs).

All newest stable stuff. (Godot 3.4, Nim 1.6.0, Godot-Nim 0.8.5)

-----------------------

I'm a beginner with both Nim and Godot, would be nice if there was more info on things to keep in mind when starting. For instance [I made a thread on r/nim](https://www.reddit.com/r/nim/comments/qodqyc/godot_for_beginner_projects_alternatives/) on my thoughts (of which the above issue is one). One of the things was that I couldn't add to certain values (for instance `position.x` as gdscript allows) but I did figure out a way to at least get something working.

Also search on the io page seems to be broken.

**Comment by endragor** [comment]
You should deal with exceptions on Nim level. If it gets propagated past your exported procedure, then you get an error message in the log. Godot doesn't support a notion of exceptions.

**Comment by insomniacUNDERSCORElemon** [comment]
The problem is that it's Nim taking issue with the signal sent from Godot. 

`Unhandled Nim exception (IndexDefect): index out of bounds, the container is empty`

Is the way I've tried to fix it not the proper way? In my function I want to check for empty data and handle that differently, but the `raises` effect/pragma isn't working for it.

**Comment by dsrw** [comment]
`raises` isn't for handling exceptions. It's a way of validating which exceptions a procedure can raise, so you can be confident that your code can't raise anything you're not prepared to handle. You may choose to use it to guard against certain kinds of bugs, but it really doesn't have anything to do with interfacing with godot-nim.

The exception you're seeing occurs before your code is called, so there really isn't anything you can do to handle it. Strings and seqs in nim worked differently when godot-nim was written (before nim 1.0), and occasionally bugs pop up as a result, particularly when dealing with 0 length strings/seqs. I opened PR #114 with a fix.

In the meantime you can try using `requires "https://github.com/dsrw/godot-nim#f2af444"` instead of `requires "godot-nim 0.8.5"`.

**Comment by insomniacUNDERSCORElemon** [comment]
> `raises` isn't for handling exceptions. It's a way of validating which exceptions a procedure can raise, so you can be confident that your code can't raise anything you're not prepared to handle

I thought it *ignored* (specified) raised exceptions, is there no way to do that to deal with issues like this in the future? This seems like a clear case of knowing the issue is there meaning that it can be dealt with (ignoring invalid input).

**Comment by dsrw** [comment]
Normally you'd put the call in a `try/except` block and handle (or not handle) the error however you want, but, unless I'm misunderstanding the issue, your code isn't really involved. The error is coming from inside `godot-nim`. If you look at the stack trace I don't think you'll see any of your files.

You're not doing anything wrong. It's a subtle incompatibility between `godot-nim` and more recent nim versions. It's something that should be fixed in `godot-nim`.

**Comment by insomniacUNDERSCORElemon** [comment]
> unless I'm misunderstanding the issue, your code isn't really involved. The error is coming from inside `godot-nim`.

Correct. I already understood that, was just wondering if there was a way that Nim allowed to get around it.

Side-note to stop me from making a separate issue, can you tell me how to change Godot settings via Nim, such as `OS.min_window_size`? The API has it as `_OS` but that gives an error w/Nim so I'm not sure if that is a bug or not.

Also even smaller is adding to like position/rotation directly (especially for stuff like `position.x`). I've figured out how to use `editSetPostion` but it's a bit clunky to use that alongsite `editGetPosition`.

(feel free to not respond if you don't know off the top of your head, also see that I opened an issue about search being broken)

**Comment by insomniacUNDERSCORElemon** [comment]
Closing as most of my issues relevant to this (other than beginner notes) are addressed. dsrw's fix worked.
