### ISSUE TITLE
Preload a scene and create instance?

### ISSUE THREAD

**Issue by jrenner** [pragmagic/godot-nim#30]
Is it possible to preload a scene and create an instance from inside Nim?

i.e. in GDScript:

```
var gameunit = preload("res://GameUnit.tscn")

func spawnUnit():
    var inst = gameunit.instance()
```

**Comment by endragor** [comment]
With GDNative there is no notion of "preloading", since the library is loaded as a whole with all the containing types. With GDScript each script is loaded separately, so there is such concept.

`load` is a method of `ResourceLoader` singleton and you can decide when exactly to load a resource. If you want to load a scene when the GDNative library is loaded (not really recommended), you can do it in global scope:

```nim
import godot
import resource_loader, packed_scene

let gameUnitScene = load("res://GameUnit.tscn") as PackedScene

gdobj GameLevel of Node:
  proc spawnUnit*() {.gdExport.} =
    let unit = gameUnitScene.instance()
```

The scene will be loaded when the library is first loaded and will reside in memory for the whole game session, which is why it's not recommended. In a real game you'd need to implement some kind of resource manager that would know when to load certain resources (usually when switching a level).

In the above example you can prepare the scene in `GameLevel`'s `ready` method  and then use it in `spawnUnit`:

```nim
import godot
import resource_loader, packed_scene

gdobj GameLevel of Node:
  var gameUnitScene: PackedScene

  method ready() =
    gameUnitScene = load("res://GameUnit.tscn") as PackedScene

  proc spawnUnit*() {.gdExport.} =
    let unit = gameUnitScene.instance()
```

**Comment by jrenner** [comment]
I see. So the best solution is probably to just keep to GDScript for things like these.

**Comment by rosshadden** [comment]
@jrenner I have done exactly what he has in his second block, and it works great.

```nim
Foo = load(path) as PackedScene
let foo = Foo.instance()
```

[Here](https://github.com/acleverpun/tankerz/blob/dev/nim/src/building.nim#L25) you can see me doing this in a tangible example, from an RTS prototype I was working on where buildings could spawn units. Check out lines 25 and 42. As you can see by looking at my [unit.nim](https://github.com/acleverpun/tankerz/blob/dev/nim/src/unit.nim) file, I didn't have to do anything special for it at all, so there's really no setup to make this work.

You really just do exactly what you had in your example question, but use `load` instead of `preload`.
As @endragor said, you would typically make a resource manager so you can do the "pre" part of preloading, and this has been something I always end up doing in gamedev. It just so happens GDScript makes it more accessible.

**Comment by jrenner** [comment]
Thanks this was all a great help.

**Comment by Skaruts** [comment]
Sorry for revamping this, but is there some way to instantiate for example a Sprite?

This doesn't seem to work.
```nim
var sprite = Sprite()

print(sprite)   # (godotObject: ..., linkedObject: ..., isRef: false, isFinalized: false, isNative: false)

sprite.hframes = 16   # gives me the error below in godot's debugger when I run the app
```

```
E 0:00:01.427   Unhandled Nim exception (NilAccessError): Could not access value because it is nil.
C:\Users\Skaruts\.nimble\pkgs\godot-0.7.26\nim\godotmacros.nim(613) methFunc
C:\Godot\Godot-Nim\rl-test\rl-test-5\src\fov.nim(34) init
C:\Godot\Godot-Nim\rl-test\rl-test-5\src\godotapi\sprite.nim(153) hframes=
C:\Users\Skaruts\.nimble\pkgs\godot-0.7.26\godotinternal.nim(19) ptrCall
```

**Comment by endragor** [comment]
You should use `gdnew` for instantiating Godot objects. So `gdnew[Sprite]()` for your example.

**Comment by Skaruts** [comment]
Oh nice. Thanks. 
Is it reference-counted too?

**Comment by endragor** [comment]
If the type inherits Reference, then yes. Otherwise, no. Nodes in particular are freed together with their parents. But if you leave a node detached from the scene tree and never free it, then it's a leak. This is similar to how GDScript and Godot work in general.

**Comment by Skaruts** [comment]
Ah ok. So I got not worries. I was aware of that kind of leak in godot as well. Thanks.

**Comment by Skaruts** [comment]
One other thing, if you don't mind: is it possible to access a gdscript custom class from Nim? So if I have `Tile.gd`, which isn't attached to a scene, and is defined with `class_name Tile`, can I somehow bring it to Nim and instantiate it? 

Also, is it possible to have a sequence of a Godot custom type like that one?
