### ISSUE TITLE
How to access fields in GDScritp from Nim?

### ISSUE THREAD

**Issue by Skaruts** [pragmagic/godot-nim#54]
Two people on discord told me `get("property_name")` works in C++, D, etc, so I am assuming it should work in Nim as well, but it didn't. From my current test project:

In Data.gd (autoloaded as "data") 
```gdscript
extends Node

export fov_radius = 42  # export isn't needed here, I just tested this with/without it
```

Then in a Nim file

```Nim
let data = self.get_tree().root.get_node("data")
print(data.get_class()) # >>> Node

print("fov_radius: ", data.get("fov_radius")) 
# runtime error: Unhandled Nim exception (NilAccessError): Could not access value because it is nil.
```

How can I make it work?

(Note: I don't necessarily need this only to access autoloaded scripts, I might want to get access to something else.)

**Comment by endragor** [comment]
There are some cases where in Godot where there is a method that starts with an underscore and the same method without it. For example, `Object` has `_get` and `get` methods. `_get` is an implementation of `get` in this case that can be overridden by descendants of `Object`. Nim procedures are not allowed to start with an underscore, so the API generator resolves this by adding `Impl` postfix to the method without starting underscore. It would probably make more sense to add it to the method _with_ underscore, but now it would be a breaking change.

So to answer you question: you should call `getImpl` instead of `get`.

**Comment by Skaruts** [comment]
Ah! That worked. :) 
Thank you.

This is the kind of thing that is making me start to dislike Nim's insensitivity to underscores. I used to be ambivalent about it, but lately I started noticing a lot of problems with it...

**Comment by endragor** [comment]
Yeah that works, but overriding `.` is not something I'd add to the library itself. But users are free to use this and other tricks in their codebase, though.

**Comment by Skaruts** [comment]
@endragor I'm having a little trouble getting a texture, though:

```nim
gdobj RLCellmap of Node2D:
    var font:Texture

    method ready*() =
        let am = self.get_tree().root.get_node("am") # AssetManager
        self.font = am.getImpl("texture")
        # Error: type mismatch: got <Variant> but expected 'Texture = ref Texture:ObjectType'
```
In some other cases I used `asInt()` and `asColor()`, but it seems those functions only exist for built-in types. I tried a few other things like `as Texture`, `asGodotObject()`, but nothing worked. Ultimately I'm guessing I need to use `fromVariant()`, and I tried that too, but I don't quite understand how to use it, because it seems to require two variants as parameters.
