### ISSUE TITLE
Update README and docs to show this works with Nim 1.2 and Godot 3.2

### ISSUE THREAD

**Issue by geekrelief** [pragmagic/godot-nim#57]
Hi I just followed the instructions for the Godot Nim stub with Nim v1.2 and Godot 3.2.1 stable and was able to run the example.  So far so good. 

I'm new to Nim and Godot, but it seems like the lack of updates to the docs, might scare people into thinking Nim isn't viable with Godot.  Can you update the README and docs?

**Comment by zetashift** [comment]
Well the docs mention Godot 0.18 or newer which is technically correct. 
The docs don't mention Godot 3.0 _or newer_.  I'm fine with adding this.

Also the lack of updates to the docs is more because I think all is done. There is nothing else to add to this (maybe a dark mode?) because the GDNative API also hasn't changed.
It might be nice to add a "Things using godot-nim" section.

**Comment by geekrelief** [comment]
Thanks. I only brought up this issue because someone on twitter had the wrong impression about this project after a cursory evaluation.  I wanted to combat the misinformation.  Btw, when Godot 4.0 is released do you think there will be any changes required for godot-nim?

**Comment by zetashift** [comment]
Yes, because I'm assuming they will break GDNative API compatibility for some nicer stuff, see relevant: https://github.com/godotengine/godot/issues/35467
I don't think the changes will be big though.

Also about the twitter thing, that's a shame, it's stable and used in production(godot-nim), there should be no need to be afraid ;).

**Comment by geekrelief** [comment]
Awesome!  Knowing this being used in production gives me some confidence to jump in and try things out. I was looking at haxe + heaps.io or haxe + gdnative until I came across nim.  And nim sounds enticing.

This is off topic, but how is debugging nim code with godot?  Do you launch the executable and attach to process with gdb or something like gdbgui?  How does hot code swapping / reloading work?

Maybe we can add this info to a wiki for new comers.  Thanks!

**Comment by zetashift** [comment]
So I do all my debugging using `echo` (Nim's equivalent of println), so I can't help you with this really, I do think it's possible as I've seen some mentions of it, it was somewhere in the realm where you can still 'attach' the debugger like normal. 
For more help/info on this I'd advise asking in the #gdnative channel on Discord or any other godot-related forum.
I could upload some godot-nim related code that works on 1.2 too for the wiki; though again I think the section can easily be added to this repo's README.

For something more detailed I think we could make a wiki or just a simple blogpost would be far enough to get some eyes on this!

As for your update: https://github.com/VPashkov/awesome-nim#game-development it's somewhat out of that, you can either make a PR or create a forum thread to start an initiative since I think a lot of people are using Nim for gamedev (relatively). 
It's getting somewhat off-topic, feel free to hop on Discord/IRC/Gitter (they are all connected so you don't miss out) of Nim to ask more: https://nim-lang.org/community.html

**Comment by geekrelief** [comment]
Cool! Thanks for the advice.
