### ISSUE TITLE
Leveraging types from nim's standard library

### ISSUE THREAD

**Issue by rosshadden** [pragmagic/godot-nim#6]
I'm curious why you didn't build on top of types from the standard library, like `Vector2d` from `basic2d` for example.  I'm not proposing it would drastically change anything, but the vector type definition seems to be identical to the standard one, and thus it could be beneficial to have access to nim's functions and overloads on them, and apply whatever Godot defines on top of that starting point.  Might be a stupid question stemming from me not being as acquainted with nim as I would like.

Also as a side question, do you frequent the godot or nim IRC rooms or something else of that nature?  A lot of the questions I have asked you could be quick conversations on IRC/IM and not pollute the issue tracker :D.

**Comment by TiberiumN** [comment]
I think it's neccessary to use Godot types because other Godot functions expect Godot types, and (maybe) converting one type to another many times can be a performance hit
Also +1 about IRC, I want to ask some questions too :)

**Comment by endragor** [comment]
Nim stdlib types use `float`, which is 64-bit float, while game engines use 32-bit floats.
The plan is to implement all Godot math types fully in Nim (it's already done for `Vector3` and `Basis`, the rest will come). That allows C compiler to optimize usage of operations on those types, which cannot be done if the operations are external. I'd like to keep API of those types consistent with Godot API and possibly add something on top, if the need arises. That's because people may also use GDScript (we do) and using two different conventions would be annoying. And likely nobody really uses Nim's stdlib types for something significant.

I'm both in Nim's and Godot's IRC channels, but I don't have bots or browse offline messages there. I'm also in Godot's Discord server, and Discord delivers offline messages just fine, so that's probably a good place. Email also works well (added to profile here).
