### ISSUE TITLE
Godot crashes after building godot-nim in existing project

### ISSUE THREAD

**Issue by DARTHVADERbn** [pragmagic/godot-nim#85]
Windows 10

at the beginning of starting project in godot everything goes well, but after 25 seconds godot starts crashing.

**Comment by zetashift** [comment]
Do you see any error in the console?
I think I had this too and it has to do with how Godot handles dll's.

**Comment by DARTHVADERbn** [comment]
> Do you see any error in the console?
> I think I had this too and it has to do with how Godot handles dll's.

Unfortunately, nothing

**Comment by zetashift** [comment]
Can you try compiling with GCC instead of VCC?

Change the `vcc` in this line: https://github.com/pragmagic/godot-nim-stub/blob/master/src/config.nims#L41 to `gcc`

**Comment by DARTHVADERbn** [comment]
ok i will try

**Comment by DARTHVADERbn** [comment]
still crashing

**Comment by zetashift** [comment]
I'm not sure how do diagnose this. I'm also not on Windows anymore, so that doesn't help. Also this might be how Godot handles DLL, I asked this in the discord and it was a hard issue to solve.

You can try to get this: https://github.com/geekrelief/gdnim running, geekrelief runs Windows at well so it's better tested. The setup takes a bit longer since you have to compile from source, but you get a lot of goodies for it!

**Comment by DARTHVADERbn** [comment]
Thanks! I will try it

**Comment by DARTHVADERbn** [comment]
after some project tests, i find out what Godot-nim scripts negatively react to GDscript scripts

so that because godot starts crashing
